### ISSUE TITLE
Переклад «Layout»

### ISSUE THREAD

**Issue by IhorHordiichuk** [webdoky/content#1]
Оскільки дискусія відбулася в кількох різних місцях, то вирішено підсумувати тут.

1. Було запропоновано «компонування», оскільки це найвдаліший прямий переклад https://e2u.org.ua/s?w=Layout&highlight=on
2. Запропоновано залишити як є.
3. Обговорено можливість вживання запозиченого типографічного терміну «верстка».

**Підсумок:**
Найуживанішим та найвідповіднішим визначено термін «верстка», на позначення результату та «верстання», на позначення процесу створення.

**Comment by AdriandeCita** [comment]
Так, дякую @IhorHordiichuk !
Для історії, прикріплюю скріншот одного з епізодів дискусії
![image](https://user-images.githubusercontent.com/11510394/126974960-c3969c96-50ed-4b30-afa2-1132d19a5e1c.png)
