### ISSUE TITLE
Management

### ISSUE THREAD

**Issue by IhorHordiichuk** [webdoky/content#11]
Пропоную позбутися перекладу «управління»

1. http://tc.terminology.lp.edu.ua/TK_Komisija/Protokol_2002_03.pdf
2. Сторінка 4, пункт 74 та примітка до нього 11 (внизу сторінки) http://tc.terminology.lp.edu.ua/TK_Komisija/Protokol_2002_04.pdf
3. Глосарій у кінці розділу http://tc.terminology.lp.edu.ua/TK_sem_WinUA.htm#Sect2
4. Переважна більшість словників пропонує керування https://e2u.org.ua/s?w=Management&dicts=all&main_only=on&highlight=on

**Comment by AdriandeCita** [comment]
Питань немає, тут справді складно щось додати. Нехай буде "керування"

**Comment by AdriandeCita** [comment]
до того ж, у нас, якщо й не помиляюся, "управління" частіше вживається в сенсі "установа", так що "керування" за всіма пунктами краще
