### ISSUE TITLE
Grave, grave accent ("`") – гравіс, тупий наголос?

### ISSUE THREAD

**Issue by undead404** [webdoky/content#246]
Вікіпедія: гравіс (LT такого слова взагалі не знає)
Англійсько-український глосарій виробів Microsoft (2006): тупий наголос
Microsoft Language Portal: дає обидва варіанти

Що будемо використовувати?

**Comment by AdriandeCita** [comment]
гравіс мені більше подобається (ну і раніше його вже вживав у перекладі). Але його трохи незручно відмінювати. Оскільки скидається, що обидва терміни цілком коректні, я б із задоволенням вживав обидва.

**Comment by AdriandeCita** [comment]
Вніс це в глосарій [feat: update glossary and rename it to avoid collision with MDN's glossary](https://github.com/webdoky/platform-next/commit/0c712961066c0b8bda82d4c9e2e437bf9690db55). Надалі тримати цю дискусію відкритою не бачу сенсу.
