### ISSUE TITLE
Comment – коментар, примітка?

### ISSUE THREAD

**Issue by undead404** [webdoky/content#247]
Вікіпедія: коментар
Англійсько-український глосарій виробів Microsoft (2006): примітка
Microsoft Language Portal: обидва варіанти

Будемо вважати глосарій Microsoft застарілим джерелом, і всюди перекладати "коментар"?

**Comment by IhorHordiichuk** [comment]
Підтримую «коментар». Він сприймається однозначніший у випадку коментарів у коді.

**Comment by undead404** [comment]
Так, давайте "коментар", бо "примітка" може означати будь-що.

**Comment by AdriandeCita** [comment]
до того ж примітка перетинається з "note" (яку у нас не прийнято називати нотаткою)

**Comment by AdriandeCita** [comment]
Вніс це в глосарій [feat: update glossary and rename it to avoid collision with MDN's glossary](https://github.com/webdoky/platform-next/commit/0c712961066c0b8bda82d4c9e2e437bf9690db55). Надалі тримати цю дискусію відкритою не бачу сенсу.
