### ISSUE TITLE
Label – етикетка, позначка, щось іще?

### ISSUE THREAD

**Issue by undead404** [webdoky/content#253]
Вікіпедія: етикетка, ярлик
Англійсько-український глосарій виробів Microsoft (2006): позначка
Microsoft Language Portal: поле, надпис, підписувати, мітка, підпис, етикетка, позначка

Який переклад буде основним?

**Comment by AdriandeCita** [comment]
Вніс це в глосарій [feat: update glossary and rename it to avoid collision with MDN's glossary](https://github.com/webdoky/platform-next/commit/0c712961066c0b8bda82d4c9e2e437bf9690db55). Надалі тримати цю дискусію відкритою не бачу сенсу.
