### ISSUE TITLE
Logo – емблема, логотип, прототип?

### ISSUE THREAD

**Issue by undead404** [webdoky/content#255]
Вікіпедія: логотип
Англійсько-український глосарій виробів Microsoft (2006): емблема, прототип
Microsoft Language Portal: емблема, логотип

Прототип явно мимо каси, а емблема і логотип видаються рівнозначними. Здається, емблема вкорінилась в українській давніше. Що думаєте?

**Comment by IhorHordiichuk** [comment]
Я б залишив «логотип», щоб уникнути проблем, якщо у реченні трапляться одночасно «logo» і «emblem».

**Comment by AdriandeCita** [comment]
В контексті вебу, вебдизайну - краще логотип. В контексті айдентики може бути емблема.
Для комерційної функції і брендингу використовується логотип. Емблема - це радше прикраса або символ з глибоким змістом.

**Comment by AdriandeCita** [comment]
Вніс це в глосарій [feat: update glossary and rename it to avoid collision with MDN's glossary](https://github.com/webdoky/platform-next/commit/0c712961066c0b8bda82d4c9e2e437bf9690db55). Надалі тримати цю дискусію відкритою не бачу сенсу.
