### ISSUE TITLE
Session – сеанс чи сесія?

### ISSUE THREAD

**Issue by undead404** [webdoky/content#256]
Вікіпедія: Пресвітерій, сесія, семестр
Англійсько-український глосарій виробів Microsoft (2006): сеанс, сесія
Microsoft Language Portal: сеанс, тимчасовий

То сесія чи сеанс?

**Comment by AdriandeCita** [comment]
Сесія. У нас просто засилля сесій на англомовному боці: і SessionStorage, і всякі [express-session](https://www.npmjs.com/package/express-session).
Сеанс можна залишити як допоміжний термін.

**Comment by undead404** [comment]
Для мене вирішальним на користь сесії є те, що прикметник "сеансний"  геть не милозвучний

**Comment by AdriandeCita** [comment]
Вніс це в глосарій [feat: update glossary and rename it to avoid collision with MDN's glossary](https://github.com/webdoky/platform-next/commit/0c712961066c0b8bda82d4c9e2e437bf9690db55). Надалі тримати цю дискусію відкритою не бачу сенсу.
