### ISSUE TITLE
Antipattern – ?!!

### ISSUE THREAD

**Issue by undead404** [webdoky/content#266]
Жаргонізм, котрого нема у словниках. Можливо, "шкідлива практика"?

**Comment by AdriandeCita** [comment]
антипатерн?

Шкідлива практика перетинатиметься з "bad practice"

**Comment by AdriandeCita** [comment]
так, патерн у нас теж не дуже поширений у словниках. Але він застосовується доволі давно, і проблем з його розумінням наче немає

**Comment by AdriandeCita** [comment]
Вніс це в глосарій [feat: update glossary and rename it to avoid collision with MDN's glossary](https://github.com/webdoky/platform-next/commit/0c712961066c0b8bda82d4c9e2e437bf9690db55). Надалі тримати цю дискусію відкритою не бачу сенсу.
