### ISSUE TITLE
Flattening (результат виклику `Array.flat()` над масивом)

### ISSUE THREAD

**Issue by AdriandeCita** [webdoky/content#29]
Варіанти: вирівнювання (на один рівень), спрощення, сплющення?

Вирівнювання мені не дуже подобається, оскільки ми трохи перевантажуємо термін. У мене взагалі перша асоціація з вирівнюванням - це "вирівнювання масиву цілих чисел" в контексті приготування даних для векторизації і роботи з SIMD. Але можливо.
Сплющення - буквальний переклад слова `flattening`, добре відображає суть процесу, але можливо звучить не дуже. Я його зустрічав деінде в документації для Ruby, і, здається, пайтону, але це не надто поширений термін

**Comment by IhorHordiichuk** [comment]
Я не готовий підтримати якийсь один варіант насправді. Я пошукав у словнику, [звідти й пропозиція](https://e2u.org.ua/s?w=flattening&dicts=all&main_only=on&highlight=on), але як буде зрозуміліше не знаю, тож і спитав, чи ба не з книги якої термін.

**Comment by AdriandeCita** [comment]
@IhorHordiichuk власне, твоє посилання також вказує на цей варіант, я одразу й не звернув уваги. Дякую!

**Comment by undead404** [comment]
"Сплощення" чудово звучить.
