### ISSUE TITLE
Trivial | Заголовок сторінки /docs/

### ISSUE THREAD

**Issue by Mezko0** [webdoky/content#303]
Привіт. Дуже крута ініціатива, радий буду допомагати. Тепер до справи. Це ніби і не критична помилка, але все ж давайте будемо намагатись все робити максимально грамотно і створювати грамнотний україномовний контент :)
В заголовку написано "Пара слів про нас", я на мене звучить трошки русняво, українською більш правильно буде писати "Кілька слів про нас" чи "Декілька слів про нас", чи до прикладу, "Коротко про нас". 
Це стосується тегу title, і заголовка h1 на сторінці.
Гарного дня!

**Comment by AdriandeCita** [comment]
Дякую, радий чути, рук нам точно не вистачає)
Зауваження доречне. Якщо маєте час та натхнення - проблемний текст знаходиться у репозиторії з платформою, конкретно отут https://github.com/webdoky/platform/blob/master/content/docs/index.md. Ймовірно знадобиться перевірити також підписи навігації в gray-matter-заголовку. Feel free to зробити пулреквест із виправленням. Ну або ми десь в одному з наступних оновлень самі виправимо :)

**Comment by AdriandeCita** [comment]
Виправлено з міграцією на нову платформу https://github.com/webdoky/platform-next/commit/e1463bc178ec2915d0b28c0549dd4bc676bb60f9
