### ISSUE TITLE
Курсор не змінюється на Pointer при наведенні на назви кореневих розділів посібника

### ISSUE THREAD

**Issue by Mezko0** [webdoky/content#432]
Найкраще це видно на відео, тому залишу його тут:
https://www.awesomescreenshot.com/video/9980441?key=3b9a7ce5993718def8e4311759da6059

**Comment by AdriandeCita** [comment]
Дякую! Додав відповідний ефект в цьому блоці змін [feat: add hovers in navigation, add CTA block in unlocalized pages](https://github.com/webdoky/platform-next/commit/391de6d44716c6f4d1ddadf957666d3d6c35d538)
