### ISSUE TITLE
Неперекладені на українську розділи сайту ніяк не виділені

### ISSUE THREAD

**Issue by Mezko0** [webdoky/content#433]
При використанні сайту я часто натикаюсь на розділи, заголовки яких відображаються в колонці навігації українською, але при переході бачу, що насправді сторінка не перекладена.
До речі, було б добре відразу там додати посилання, за яким людина може перейти і приступити до перекладу тої сторінки. Або це може бути якийсь заклик чи пропозиція долучитись до ініціативи. Оскільки там ітак є посилання на першоджерело англійською і передбачається, що юзер піде його вичитувати
[Картинка](https://www.awesomescreenshot.com/image/30174974?key=50f0da527c56c4d070dd0bc3d27bcb5b
)
[Картинка](https://tinyurl.com/2dzv5teg)

**Comment by AdriandeCita** [comment]
Щодо блока із закликом до дії на таких сторінках - ідея дуже доречна, дякую! Для початку я додав першу версію отут [feat: add hovers in navigation, add CTA block in unlocalized pages](https://github.com/webdoky/platform-next/commit/391de6d44716c6f4d1ddadf957666d3d6c35d538), з часом можливо розвинемо ідею.

Що ж до посилань в навігації - з цим складніше, там дещо більше етапів обробки вмісту. Буду іще думати

**Comment by undead404** [comment]
Уже ж виділені?

**Comment by AdriandeCita** [comment]
@undead404 іще в навігації треба зробити
![image](https://user-images.githubusercontent.com/11510394/203839845-a3520081-a4da-463d-a287-46caeebfae06.png)

**Comment by AdriandeCita** [comment]
Реалізовано в рамках цього ПР https://github.com/webdoky/platform-next/pull/38
