### ISSUE TITLE
Деструктурування -> деструктуризація

### ISSUE THREAD

**Issue by AdriandeCita** [webdoky/content#494]
Контекст: [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment).

`Деструктуризація` - часто зустрічається, прижилося в деяких інших областях (хімія - "деструктуризаця білків"), а також у інших формах ("реструктуризація" === "реорганізація"). У переглянутих словниках відсутній, але трапляється у формі без префікса: https://slovnyk.ua/index.php?swrd=%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D1%96%D1%8F, https://slova.com.ua/word/%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D1%96%D1%8F

`Деструктурування` - теж часто зустрічається (здається, в психології, лінгвістиці?), присутній у словниках.

Переваги від переходу до вживання терміну "деструктурування":
- Ця форма здається більш характерною для української мови
- Ця форма не звучить як расійське "дєструктурізация". Це і добре (ми не будемо змішуватися зі російськомовною видачею), і погано (те саме, ми не будемо з'являтися в російськомовній видачі)

**Comment by AdriandeCita** [comment]
Залишаю тут радше для історії, все ж якийсь час було витрачено на пошук цих посилань)

Але якщо у когось є кращі аргументи - я б з ними радо ознайомився

**Comment by undead404** [comment]
Для мене іще стало аргументом, що javascript.info використовує саме "деструктурування"

https://uk.javascript.info/destructuring-assignment

**Comment by AdriandeCita** [comment]
Іще Довгань використовує цю форму https://understandinges6.denysdovhan.com/manuscript/05-Destructuring.html

**Comment by AdriandeCita** [comment]
Натомість, перший варіант, із такого більш-менш відомого, зустрічається на кодгайді https://codeguida.com/post/1480

**Comment by AdriandeCita** [comment]
Вніс це в глосарій [feat: update glossary and rename it to avoid collision with MDN's glossary](https://github.com/webdoky/platform-next/commit/0c712961066c0b8bda82d4c9e2e437bf9690db55). Надалі тримати цю дискусію відкритою не бачу сенсу.
