### ISSUE TITLE
Переклад /en-US/docs/Web/HTML/Element/ul

### ISSUE THREAD

**Issue by AdriandeCita** [webdoky/content#64]
Текстовий вміст сторінки знаходиться тут: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul
Первісні сирці лежать тут: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/ul/index.md

**Comment by Keira79** [comment]
Done

**Comment by AdriandeCita** [comment]
Зроблено тут https://github.com/webdoky/content/pull/114
