### ISSUE TITLE
Переклад /en-US/docs/Web/HTML/Block-level_elements

### ISSUE THREAD

**Issue by AdriandeCita** [webdoky/content#65]
Текстовий вміст сторінки знаходиться тут: https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements
Первісні сирці лежать тут: https://github.com/mdn/content/blob/main/files/en-us/web/html/block-level_elements/index.md

**Comment by Keira79** [comment]
Переклад на ревью.

**Comment by AdriandeCita** [comment]
Зроблено тут https://github.com/webdoky/content/pull/112
