### ISSUE TITLE
Переклад /en-US/docs/Web/HTML/Element/hr

### ISSUE THREAD

**Issue by AdriandeCita** [webdoky/content#66]
Текстовий вміст сторінки знаходиться тут: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr
Первісні сирці лежать тут: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/hr/index.md

**Comment by AdriandeCita** [comment]
KeiraMoore is working on it

**Comment by Keira79** [comment]
Переклад на рев'ю

**Comment by AdriandeCita** [comment]
Зроблено https://github.com/webdoky/content/pull/110
